### ISSUE TITLE
MCAP sinks sometimes fail

### ISSUE THREAD

**Issue by henrygerardmoore** [facontidavide/data_tamer#2]
I modified `example.cpp`, with the **only** change being that I used an MCAP sink instead of the dummy sink. Sometimes with this change (not always), the program will fail with the following error.

```
[henry-picknik-laptop][add_example] data_tamer$ ./build/Debug/examples/example 
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Aborted (core dumped)
```

This also happens sometimes (but seems to be more rare) in Release mode:
```
[henry-picknik-laptop][add_example] data_tamer$ ./build/Release/examples/example 
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Aborted (core dumped)
``` 

Here's a screenshot of my code modifications
![image](https://github.com/facontidavide/data_tamer/assets/44307180/03950b6e-773d-4f6c-ae4b-f8da12407538)

**Comment by facontidavide** [comment]
fixed. thanks!
